### ISSUE TITLE
package.json misses various dependencies

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#1]
`npm install` does not install (but should) the following:

- axios
- crypto-js
- js-sha3

**Comment by HilKai** [comment]
First time working with npm so any reference as to how to implement dependencies into packages is appreciated

**Comment by MarHai** [comment]
https://docs.npmjs.com/getting-started/using-a-package.json and https://stackoverflow.com/questions/19578796/what-is-the-save-option-for-npm-install
