### ISSUE TITLE
.data does not work

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#12]
`data` properties are not fetched correctly (or: not at all). I assume that the following line must be changed 

https://github.com/HilKai/FBForschung/blob/fca720ad42ff74c81031e068ada6098346544ba3/src/scripts/background.js#L321

into 

` currentObject[config.column] = domNode.dataset[dataObjStr];`

**Comment by HilKai** [comment]
syntax should be correct, however there is a missmatch between the config and the product specification as  data is defined as : "data-XYZ: ein Data-Attribut des HTML-Elements (getData(XYZ))" however the config uses i.e "attr-data-utime"

**Comment by MarHai** [comment]
Uh, okay, that makes sense. I'll investigate.

**Comment by MarHai** [comment]
Should work now, server-side. Please re-check client-sided.

**Comment by HilKai** [comment]
cant currently be tested as the only data object is timestamp and that css selector is returning no objects

**Comment by MarHai** [comment]
The current config works, indeed:
`$$('abbr.timestamp[data-utime]')[0].dataset['utime']`

**Comment by HilKai** [comment]
should be fixed for utime, im not sure if this is fixed for everything, though I did change the code to include all data options
