### ISSUE TITLE
config attribute "count" seems wrong, please re-check

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#21]
It should return the number of found elements through the given selector

**Comment by HilKai** [comment]
It seems like count is only implemented in dev config, however there is a css selector on the body, under closer inspection you can see that we only pass the inner content of the body to be validated so css selecting on the body doesnt return anything, I have tried to change this to "_li" in the dev config, however it seems like my css selector knowledge is limited as this returns nothing aswell, in the current status I cant replicate any counting action as long as we dont have a working dev config to test with

**Comment by MarHai** [comment]
I don't understand the problem. Do you need a test config? If so, there is one in the live config, named "Anzahl sichtbare Kommentare" (#40).
