### ISSUE TITLE
extend config option to be an IF

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#22]
Apart from being a post or not, config options should also be capable of being an IF. If a config option is an IF, it is equipped with the usual (selector and type) but also with a comparison (==, !=, <, <=, >, >=, ~ ...) and a value to compare with. If this IF then fails to pass, all the branches below this IF (in the hierarchical tree structure of the config) are ignored.

This is not yet implemented on the server, so I'll go first on this and then comment here again in order to communicate specifics.

**Comment by MarHai** [comment]
waiting for #12 in order to see whether tooltipContent translates into posttype

**Comment by MarHai** [comment]
Alright, here we go: Every configuration element now has an `if` option of type boolean. If `if` is true, then four other options are also available, `if_css`, `if_attribute`, `if_comparison`, and `if_value`. In case, `if` is true, this element should then, first, evaluate a selector (in the currently given context), and only if this evaluation turns out to be successful, continue (with both storing data and proceeding with child elements).

Here's how the evaluation should look like (only if `if` is true):

1. find the element(s) using the selector that has been submitted in `if_css`
2. collect this/these element(s) values as configured in `if_attribute` (these two steps are completely similar to current data-fetching procedures; they only build on two new/different configuration fields)
3. compare the found result in one of many comparison types (see below) with the value as given in `if_value` (for example, the comparison could be that the found result should be greater than 3, then `if_comparison` would be `greater than` and `if_value` would be `3`)
4. if, and only if, this comparison is successful (for example, if the value is actually greater than 3), then proceed with collecting the actual values (as set in `css`/`attribute`/...) and with proceeding to child elements

Comparison types:

- `equal` means that the comparison is successful if the found result `== if_value`
- `unequal` means that the comparison is successful if the found result `!= if_value`
- `gt` means that the comparison is successful if the found result `> if_value`
- `gteq` means that the comparison is successful if the found result `>= if_value`
- `lt` means that the comparison is successful if the found result `< if_value`
- `lteq` means that the comparison is successful if the found result `<= if_value`
- `contains` means that the comparison is successful if `if_value` appears somewhere in the found result, something like `result.indexOf(if_value) >= 0`
- `notcontains` means that the comparison is successful if `if_value` does not appear anywhere in the found result, something like `result.indexOf(if_value) < 0`
- `regex` means that the comparison is successful if the in `if_value` given regular expression matches the found result, something like `(new RegExp(if_value)).test(result) == true`
- `notregex` means that the comparison is successful if the in `if_value` given regular expression does not match the found result, something like `(new RegExp(if_value)).test(result) == false`

**Comment by MarHai** [comment]
There seem to be some issues with this as I get all what I want through manual filtering but not via the plugin. Please re-check.

**Comment by HilKai** [comment]
there seems to be something wrong with the config,
for example testing if the shared content is public:
we use the css selector 
#stream_pagelet div[role="feed"] [data-testid="fbfeed_story"][id*="hyperfeed_story_id_"] .userContentWrapper
to get the node we want to,
then we apply ._42ef ._6a ._6a div[data-tooltip-content*="Geteilt mit"]
this return another element. The config now asks for the dataset "tooltip-content", this doesnt exist.

After I changed the config if_attribute from data-tooltip-content to data-tooltipContent any post that is shown only to friends isnt submitted anymore

Are there any other instances of the plugin filtering incorrectly? I only checked the not submitting private posts part

**Comment by MarHai** [comment]
Got it, you are right.
