### ISSUE TITLE
make registration process safer

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#24]
We need to make sure that we do not capture data from people who have not agreed to take part in the experiment. Also, people should be able to re-join their data collection on a re-install (also on a different computer/browser).

Hence ...

- [ ] If, during registration (`.../register`), the server returns a 403 ("Identifier already registered") with a `uid` given, this setup should be used (the `uid` is the plugin's `uid`). Any other error during the registration process should still be notified. No error, of course, remains unchanged.
- [x] The registration process should ensure that the user currently is logged into Facebook. The server then attaches the next Facebook session's user uid to this plugin and only captures data if this same user is logged in.
- [x] After registration, Facebook needs to be called.

**Comment by MarHai** [comment]
For the multi-step appraoch for registration, see commit https://github.com/HilKai/FBForschung/commit/d3c3f2cb14d8121a9e000a66caa3f4becb0ce5fb

**Comment by HilKai** [comment]
is bullet point 1 olready implemented? 
If im reading it correctly this code snippet from the registration function already does this:

  if (error.response.status === 403){
                    getConfig();
   } else {

**Comment by MarHai** [comment]
I did not change anything there. Both cases (with and without UID) return a 403. However, if the UID is given, this setup should be used. If the 403 does not contain an UID, then an error should be shown.
