### ISSUE TITLE
clicking "fbforschung.de/login" in the plugin's popup does not work

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#25]
When clicking the fbforschung.de/login link on the plugin's popup (i.e., after clicking the owl icon) brings up some internal template website rather than what it should bring up. Expected result:

- if a user is logged in, the link should direct to https://fbforschung.de/login/plugin/abc12xy where _abc12xy_ is the currently logged in user's identification
- if no user is currently logged in, the link should direct to https://fbforschung.de/login

**Comment by HilKai** [comment]
only not logged in users wasn't working
