### ISSUE TITLE
Chrome - logs posts into previous session instead of making new one

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#33]
even when tab or browser is closed completely inbetween

**Comment by pheliaweiss** [comment]
read issue #29 - wasn't over an hour ago

**Comment by MarHai** [comment]
Okay, to sum it up: New sessions have to be started as soon as Facebook is loaded (otherwise the ordinal numbering of posts is mixed up). That is, whenever the page is refreshed or the browser is started or a new tab is opened.

**Comment by HilKai** [comment]
should be fixed now, its a bit of a workaround but when you visit facebook your last session gets set to be in 1970 and a new session will be requested (via submitting a new post without a session id

**Comment by pheliaweiss** [comment]
Win8: works only if browser is closed completely, if tab is closed or I log out and in of facebook the posts still get logged into the previous session

**Comment by pheliaweiss** [comment]
on Mac it works when tab is closed

**Comment by HilKai** [comment]
this shouldnt be related to a windows version - is your chrome up to date on the w8 machine?

**Comment by pheliaweiss** [comment]
it should be since I installed the latest version only a few days before
