### ISSUE TITLE
logs only first 2 posts on first try, if you scroll down the newsfeed again several posts are in twice

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#37]

**Comment by MarHai** [comment]
Duplicate posts most likely is a server issue --> @MarHai
Scrolling/not scrolling is most likely a plugin issue --> @HilKai

**Comment by HilKai** [comment]
loging the first 2 posts is a limitation on the end of facebook (you only load 2 posts when visiting the page) more posts are loaded as neccesary - we detect those new posts when scrolling
