### ISSUE TITLE
Dropdown layout partly destroyed on Chrome

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#38]
When clicking the owl in Chrome, the window should be wider in order to fully show the headline and to be more readable. Also, if temporarily deactivated, "###" instead of the most recent config version appears. Lastly, what happened to the idea that messages should appear and be listed in this popup?

![image](https://user-images.githubusercontent.com/6008188/37842845-9a6b495c-2ec3-11e8-8bfa-d478760de8aa.png)

**Comment by HilKai** [comment]
made the window wider

only messages that are currently shown (but not yet marked as read or sent as email) are shown here
