### ISSUE TITLE
Firefox - owl is invisible (only on facebook)

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#40]

**Comment by HilKai** [comment]
can you specify in witch browser

**Comment by pheliaweiss** [comment]
the latest version of firefox on win 8

**Comment by HilKai** [comment]
couldn't replicate this - could you explain step by step how you installed the plugin?

**Comment by pheliaweiss** [comment]
I installed the xpi-file via Add-ons > gear-wheel > install Add-on from file. the owl is grey as usual when I am on another site but when I visit facebook it disappears. The button is still there, just without the icon

**Comment by HilKai** [comment]
okay you are a bit ahead on me for that one, could you explain how you got the xpi file - im currently testing in firefox via debug_addons and loading in the manifest.json

**Comment by MarHai** [comment]
You need to sign the addon online (but do not publish it):

- https://developer.mozilla.org/en-US/Add-ons/Distribution
- https://addons.mozilla.org/developers/addon/submit

One error shows up with last week's version, requiring you to change the GUID to something more telling. Find last week's version under http://fbforschung.de/res/download/fbforschung_firefox.xpi

**Comment by HilKai** [comment]
could you explain that GUID step a littler closer - cant seem to find where to change it

**Comment by MarHai** [comment]
1. Build/deploy the plugin.
1. Open and edit manifest.json inside (!) dist/firefox.zip and change the gecko/id to "plugin-ff@fbforschung.de"
1. Upload dist/firefox.zip to https://addons.mozilla.org/developers/addon/submit
1. Download the newly created/signed .xpi file

**Comment by HilKai** [comment]
should be fixed after reorganizing images
