### ISSUE TITLE
Firefox - when add-on is loaded temporarily, fbforschung sign-in opens only after clicking 'reload'

### ISSUE THREAD

**Issue by pheliaweiss** [HilKai/FBForschung#42]

**Comment by pheliaweiss** [comment]
also, I wasn't asked if I was logged in to facebook

**Comment by pheliaweiss** [comment]
if add-on is installed from the xpi-file the sign-in works properly - but the logging of the posts doesn't

**Comment by HilKai** [comment]
I couldn't reproduce either of these, while testing with the xpi file I got all posts: https://fbforschung.de/admin/plugins/187/sessions/352/posts

and when testing with debug addon I get a sing if aswell, please retest and reopen this issue if the bug still persists
