### ISSUE TITLE
Is the Dev-Config-Pull already implemented?

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#6]
If so, where can that be set?

**Comment by HilKai** [comment]
not currently implemented as neither about:config nor about:flags can be accesed by an extension.
Possible workaround could be manually setting a flag in the local storage via a storage-explorer (https://github.com/jusio/storage-area-explorer)

**Comment by MarHai** [comment]
Hmm, how about something like an Option's page? https://developer.chrome.com/extensions/optionsV2 Are there similar things for other browsers?

**Comment by MarHai** [comment]
also see #14
