### ISSUE TITLE
submit posts' ordinal/onscreen position automatically

### ISSUE THREAD

**Issue by MarHai** [HilKai/FBForschung#8]
For every single post that is fetched, both `position_ordinal` and `position_onscreen` should be included/submitted automatically to the server.

- `position_ordinal` is a number that just counts from top to bottom and tells the server that a post is the (for example) third post currently shown on screen.
- `position_onscreen` is the pixel offset for a post element from the very top of the page (not the offset to the browser; this should correspond to the `scrolled_until` number). Usually, one can achieve this through `document.getElementById(…).getBoundingClientRect().top - document.body.getBoundingClientRect().top`

**Comment by MarHai** [comment]
For `position_ordinal` you can just include `(i+1)` in the post object to be submitted.
https://github.com/HilKai/FBForschung/blob/7d8af1713e9db12d342bb343e60c43cf96d10693/src/scripts/background.js#L296

**Comment by HilKai** [comment]
added position_ordinal
still have to think about a good way to implement position_onscreen though

**Comment by MarHai** [comment]
Since this is not Facebook-specific, you can take the post as specified in the configuration and hard-code the calculation of the pixel offset from the very top of the page (see above).
